base/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteView, CustomLoginView
from django.contrib.auth.views import LogoutView
app_name = 'base'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name='task-delete'),
    
]

todolistprj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['complete']

base/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView

from .models import Task

class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('base:tasks')




class TaskList(ListView):
    model = Task 
    context_object_name = 'tasks'


class TaskDetail(DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'


class TaskCreate(CreateView):
    model = Task
    fields = '__all__' 
    success_url = reverse_lazy('base:tasks')


class TaskUpdate(UpdateView):
    model = Task
    fields = '__all__' 
    success_url = reverse_lazy('base:tasks')


class DeleteView(DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('base:tasks')

base/templates/base/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Login</h1>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Login">
    </form>
</body>
</html>

base/templates/base/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Task : {{task}}</h1>
</body>
</html>

base/templates/base/task_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'base:tasks' %}">Go back</a>

    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete this task? "{{task}}"</p>
        <input type="submit" value="Delete"/>
    </form>
</body>
</html>

base/templates/base/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Task Form</h3>
    <a href="{% url 'base:tasks' %}">Go Back</a>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" value="Submit">
    </form>
</body>
</html>

base/templates/base/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if request.user.is_authenticated %}
    <p>{{request.user}}</p>
    <a href="{% url 'base:logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'base:login' %}">Login</a>
    {% endif %}
    <hr>
    <h1>My To Do List</h1>
    <a href="{% url 'base:task-create' %}">Add Task</a>
    <table>
        <tr>
            <th>Item</th>
            <th></th>
            <th></th>
        </tr>
        {% for task in tasks %}
        <tr>
            <td>{{task.title}}</td>
            <td><a href="{% url 'base:task' task.id %}">View</a></td>
            <td><a href="{% url 'base:task-update' task.id %}">Edit</a></td>
            <td><a href="{% url 'base:task-delete' task.id %}">Delete</a></td>
        </tr>
        {% empty %}
         <h3>No items in list</h3>
        {% endfor %}
    </table>
</body>
</html>